In [1]:
from sklearn.feature_extraction.text import TfidfVectorizer



In [2]:
import pandas as pd

#read the data into a pandas dataframe
df = pd.read_csv("hindi_train_val_utf.csv",encoding = "UTF-8")
print(df.shape)
df.head(5)

(20183, 2)


label                                       text
0      0              भीड़ में  बहुत  हब्सी मिलेंगे
1      0  साले बेवकूफ अपनी मां मक्खियां  तो हटा दें
2      0           बुर देदो तो मुह में लंड ले लो तो
3      0       कुत्ता वहा है चिल्ला तू क्यों रहा है
4      1  चाय नहीं पीता हूं मैं इसी को छोड़ दिया ok

In [3]:
#check the distribution of labels 
df['label'].value_counts()

0    10527
1     9656
Name: label, dtype: int64

In [4]:
# df['label_num'] = df['label'].map({
#     'Household' : 0, 
#     'Books': 1, 
#     'Electronics': 2, 
#     'Clothing & Accessories': 3
# })

#checking the results 
df.head(5)

label                                       text
0      0              भीड़ में  बहुत  हब्सी मिलेंगे
1      0  साले बेवकूफ अपनी मां मक्खियां  तो हटा दें
2      0           बुर देदो तो मुह में लंड ले लो तो
3      0       कुत्ता वहा है चिल्ला तू क्यों रहा है
4      1  चाय नहीं पीता हूं मैं इसी को छोड़ दिया ok

In [5]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    df.text, 
    df.label, 
    test_size=0.2, # 20% samples will go to test dataset
    random_state=2022,
    stratify=df.label
)



# from sklearn.model_selection import train_test_split

# X_train, X_test, y_train, y_test = train_test_split(
#     df.Text, 
#     df.label_num, 
#     test_size=0.2, # 20% samples will go to test dataset
#     random_state=2022,
#     stratify=df.label_num
# )

In [6]:
print("Shape of X_train: ", X_train.shape)
print("Shape of X_test: ", X_test.shape)

Shape of X_train:  (16146,)
Shape of X_test:  (4037,)


In [7]:
X_train.head()

18373    घर मे गाय रखो उनकी सेवा करो दूध पीओ, गोबर से उ...
7111     राकेश सरकार में नहीं हैं और न ही कोई प्रशासनिक...
963      #मोहब्बत तो कर लूं #मैं_आप से मगर #मैङम,  हम #...
4371     क्या बात है, कुत्ते को शेर की खाल पहना देने से...
16455                            बूढ़े तुझे भी चैन नहीं है
Name: text, dtype: object

In [8]:
y_train.value_counts()

0    8421
1    7725
Name: label, dtype: int64

In [9]:
y_test.value_counts()

0    2106
1    1931
Name: label, dtype: int64

In [10]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.pipeline import Pipeline
from sklearn.metrics import classification_report

#1. create a pipeline object
clf = Pipeline([
     ('vectorizer_tfidf',TfidfVectorizer()),    
     ('KNN', KNeighborsClassifier())         
])

#2. fit with X_train and y_train
clf.fit(X_train, y_train)


#3. get the predictions for X_test and store it in y_pred
y_pred = clf.predict(X_test)


#4. print the classfication report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.62      0.80      0.70      2106
           1       0.68      0.46      0.55      1931

    accuracy                           0.64      4037
   macro avg       0.65      0.63      0.62      4037
weighted avg       0.64      0.64      0.62      4037



In [11]:
X_test[:5]

8070                                 पेल दिया घोड़ी बना कर
3031                                      गेल 14 चुप हो जा
7800     रोती हुई आँखो मे इंतेज़ार होता है​; ​ना चाहते ...
11404                                   याकी की ईमज ईसीआरम
5806     अभी तो धुआँ आगे से निकल रहा है कुछ समय बाद पीछ...
Name: text, dtype: object

In [12]:
y_test[:5]

8070     0
3031     0
7800     1
11404    1
5806     1
Name: label, dtype: int64

In [13]:
y_pred[:5]

array([0, 0, 1, 1, 1], dtype=int64)

In [14]:
our_test_content=['बहनचोद हे तू ',
    'तू मादरचोद हे ',
    'तेरी माँ सोती हे मेरे साथ ',
    'आजा मजे करते हे',
    "सो लौड़े हे"]

In [15]:
y_pred = clf.predict(our_test_content)

In [16]:
y_pred[:]

array([0, 0, 0, 0, 0], dtype=int64)

In [17]:
y_pred[:]

array([0, 0, 0, 0, 0], dtype=int64)

In [21]:
import pickle
with open('model_pickle','wb') as f:
    pickle.dump(clf,f)